<a href="https://colab.research.google.com/github/lakhanpal185/machin-learning-with-python/blob/main/numpy_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

x = np.arange(1,11)
print(x)

print("addtion + operation : ",x+2)
print("subtaration - operation : ",x-2)
print("multiplcation * operation : ",x*2)
print("divide / operation : ",x/2)
print("modulo % operation : ",x%2)
print("// operation : ",x//2)
print("addtion + operation : ",x+2)

arr = np.zeros(6,dtype="int")
print(arr)

arr = np.ones(7)
print(arr)


[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]
addtion + operation :  [ 3  4  5  6  7  8  9 10 11 12]
subtaration - operation :  [-1  0  1  2  3  4  5  6  7  8]
multiplcation * operation :  [ 2  4  6  8 10 12 14 16 18 20]
divide / operation :  [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
modulo % operation :  [1 0 1 0 1 0 1 0 1 0]
// operation :  [0 1 1 2 2 3 3 4 4 5]
addtion + operation :  [ 3  4  5  6  7  8  9 10 11 12]
[0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.ones((10,10),dtype='int')
print(arr)
x = np.full((5,5),12,dtype ='int')
print(x)
x = np.eye(5,8,3,dtype='int')
print(x)

arr = np.random.random((5,5))
print(arr)

np.random.seed(2)
arr = np.random.randint(5,10,(5,5))
print(arr)


[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[0.29701836 0.28786882 0.11619332 0.18172704 0.49428977]
 [0.56576513 0.22183517 0.76749117 0.57730807 0.16782331]
 [0.36747137 0.46867358 0.65426618 0.79308974 0.66306179]
 [0.61302969 0.990852   0.1194848  0.14856478 0.85228103]
 [0.50952588 0.21726993 0.99326629 0.31529748 0.25873317]]
[[5 5 8 7 8]
 [5 7 6 8 7]
 [9 9 9 8 9]
 [7 8 8 7 6]
 [7 9 8 5 9]]


In [ ]:
arr = np.random.randint(1,10,(5,5))
print(arr)
print(f"the max value of array is {np.max(arr)}")
print(f"the min value of array is {np.min(arr)}")
print(f"the min value of rows is {np.min(arr,axis = 1)}")
print(f"the min value of colum is {np.min(arr,axis = 0)}")

print(f"the max value of row is {np.max(arr,axis = 1)}")
print(f"the mean value of matrix is {np.mean(arr)}")
print(f"the mean values of rows is {np.mean(arr,axis = 1)}")



[[6 3 6 7 2]
 [6 1 6 5 9]
 [4 8 6 5 6]
 [3 7 1 6 8]
 [2 7 8 1 2]]
the max value of array is 9
the min value of array is 1
the min value of rows is [2 1 4 1 1]
the min value of colum is [2 1 1 1 2]
the max value of row is [7 9 8 8 8]
the mean value of matrix is 5.0
the mean values of rows is [4.8 5.4 5.8 5.  4. ]


In [ ]:
#trignomatrix functions
arr = np.random.randint(1,9,(5,5))
print(arr)
print(f"sin of every element is {np.sin(arr)}")
print(f'cos of every element is {np.cos(arr)}')
print(f'tan of every element is {np.tan(arr)}')
#print(f'cos of every element is {np.cos(arr)}')

[[3 6 8 6 5]
 [5 3 1 7 7]
 [1 6 7 4 2]
 [6 2 6 2 5]
 [2 8 1 4 5]]
sin of every element is [[ 0.14112001 -0.2794155   0.98935825 -0.2794155  -0.95892427]
 [-0.95892427  0.14112001  0.84147098  0.6569866   0.6569866 ]
 [ 0.84147098 -0.2794155   0.6569866  -0.7568025   0.90929743]
 [-0.2794155   0.90929743 -0.2794155   0.90929743 -0.95892427]
 [ 0.90929743  0.98935825  0.84147098 -0.7568025  -0.95892427]]
cos of every element is [[-0.9899925   0.96017029 -0.14550003  0.96017029  0.28366219]
 [ 0.28366219 -0.9899925   0.54030231  0.75390225  0.75390225]
 [ 0.54030231  0.96017029  0.75390225 -0.65364362 -0.41614684]
 [ 0.96017029 -0.41614684  0.96017029 -0.41614684  0.28366219]
 [-0.41614684 -0.14550003  0.54030231 -0.65364362  0.28366219]]
tan of every element is [[-0.14254654 -0.29100619 -6.79971146 -0.29100619 -3.38051501]
 [-3.38051501 -0.14254654  1.55740772  0.87144798  0.87144798]
 [ 1.55740772 -0.29100619  0.87144798  1.15782128 -2.18503986]
 [-0.29100619 -2.18503986 -0.29100619 -2.

In [ ]:
# lograthemic values 
arr = np.arange(2,10,1)
print(f"the log value of  {np.log(arr)} array element\n")
print(f"the log base 2 value of  {np.log2(arr)} array element\n")
print(f"the log base 10 value is {np.log10(arr)}\n")
print(arr)

the log value of  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458] array element

the log base 2 value of  [1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925  ] array element

the log base 10 value is [0.30103    0.47712125 0.60205999 0.69897    0.77815125 0.84509804
 0.90308999 0.95424251]

[2 3 4 5 6 7 8 9]


In [ ]:
yarr = np.arange(1,20,2)
print(yarr)
print(yarr.ndim)
print(yarr.dtype)
print(yarr.itemsize)
print(yarr.nbytes)

[ 1  3  5  7  9 11 13 15 17 19]
1
int64
8
80


In [ ]:
np.random.seed(1)
arr = np.random.randint(1,20,(5,5))
print(arr)
sub_arr = arr[0:3,0:3]
#             row:colum,row:colum
print(sub_arr)
#sub array updation can change the value of orginal array
sub_arr = arr[0:3,0:3].copy()
sub_arr[0][0] = 30
print(sub_arr)
print(arr)
print(np.__version__)

[[ 6 12 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 14  7]
 [19  6 19 12 11]
 [15 19  5 10 18]]
[[ 6 12 13]
 [12  6 16]
 [ 2 13  8]]
[[30 12 13]
 [12  6 16]
 [ 2 13  8]]
[[ 6 12 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 14  7]
 [19  6 19 12 11]
 [15 19  5 10 18]]
1.21.6


In [ ]:
#concatenation in python 
temparr = np.random.randint(1,10,(2,2))
print(temparr)
temparr = np.concatenate([temparr,temparr])
print(temparr)
temparr = np.concatenate([temparr,temparr],axis = 1)
print(temparr)

[[2 4]
 [5 9]]
[[2 4]
 [5 9]
 [2 4]
 [5 9]]
[[2 4 2 4]
 [5 9 5 9]
 [2 4 2 4]
 [5 9 5 9]]


In [ ]:
#rearrange the array using .reshape
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
