In [1]:
from sklearn.datasets import make_classification
import torch

In [5]:
X , y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [14]:
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)


TypeError: expected np.ndarray (got Tensor)

In [23]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [24]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [17]:
from torch.utils.data import Dataset, DataLoader

In [18]:
class CustomDataset(Dataset):
    def __init__(self,x,y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self,idx):
        return  self.x[idx] , self.y[idx]

In [20]:
dataset = CustomDataset(X,y)

In [21]:
len(dataset)

10

In [27]:
dataset[9]

(tensor([-0.5872, -1.9717]), tensor(0.))

In [30]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [31]:
for batch_feature, batch_label in dataloader:
    print(batch_feature)
    print(batch_label)
    print("_"*40)

tensor([[ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([1., 0.])
________________________________________
tensor([[-1.1402, -0.8388],
        [-1.9629, -0.9923]])
tensor([0., 0.])
________________________________________
tensor([[1.7774, 1.5116],
        [1.8997, 0.8344]])
tensor([1., 1.])
________________________________________
tensor([[-2.8954,  1.9769],
        [ 1.0683, -0.9701]])
tensor([0., 1.])
________________________________________
tensor([[-0.7206, -0.9606],
        [-0.9382, -0.5430]])
tensor([0., 1.])
________________________________________
