# Using layers from NN Module

In [5]:
import torch.nn as nn
import torch

In [6]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.layer_1 = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, data):
        out = self.layer_1(data)
        out = self.sigmoid(out)
        return out


In [7]:
# create dataset
dataset = torch.rand(10,5)

In [9]:
#creating the model
model = Model(dataset.shape[1])

In [10]:
#doing forward pass
model(dataset)

tensor([[0.6369],
        [0.5612],
        [0.5891],
        [0.5795],
        [0.5759],
        [0.5915],
        [0.6176],
        [0.5321],
        [0.6424],
        [0.5339]], grad_fn=<SigmoidBackward0>)

In [11]:
model.layer_1.weight

Parameter containing:
tensor([[ 0.0415,  0.3867,  0.2501, -0.2669, -0.2094]], requires_grad=True)

In [12]:
!pip install torchinfo

In [17]:
from torchinfo import summary
summary(model,input_size=(10,5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container

In [18]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [19]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6902],
        [0.6399],
        [0.6127],
        [0.6679],
        [0.7027],
        [0.6260],
        [0.6129],
        [0.6513],
        [0.6490],
        [0.6309]], grad_fn=<SigmoidBackward0>)

# Training using NN module components
* Optimizer
* Loss function
* Layers

In [47]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


#data preparation
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [48]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [49]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [50]:
X_train,X_test, y_train, y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [51]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [52]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [53]:
y_train

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,

In [54]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

# Designing the model architecture

In [67]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, data):
        out = self.network(data)

        return out

In [68]:
learning_rate = 0.01
num_epochs = 100

loss_fn = nn.BCELoss()

# Training


In [73]:
model = Model(X_train_tensor.shape[1])

optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

for epoch in range(num_epochs):

    y_pred = model(X_train_tensor)

    loss = loss_fn(y_pred.squeeze(1),y_train_tensor)
    print(f'Epoch: {epoch} Loss: {loss.item()}')
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



Epoch: 0 Loss: 0.6519220471382141
Epoch: 1 Loss: 0.6295158863067627
Epoch: 2 Loss: 0.6054943203926086
Epoch: 3 Loss: 0.5806744694709778
Epoch: 4 Loss: 0.5552915930747986
Epoch: 5 Loss: 0.5296344757080078
Epoch: 6 Loss: 0.5041700601577759
Epoch: 7 Loss: 0.47898662090301514
Epoch: 8 Loss: 0.45436525344848633
Epoch: 9 Loss: 0.4304666817188263
Epoch: 10 Loss: 0.40745779871940613
Epoch: 11 Loss: 0.38543570041656494
Epoch: 12 Loss: 0.3644554913043976
Epoch: 13 Loss: 0.3445333242416382
Epoch: 14 Loss: 0.325699120759964
Epoch: 15 Loss: 0.30798202753067017
Epoch: 16 Loss: 0.2913646996021271
Epoch: 17 Loss: 0.2757982313632965
Epoch: 18 Loss: 0.26122257113456726
Epoch: 19 Loss: 0.24762000143527985
Epoch: 20 Loss: 0.23493064939975739
Epoch: 21 Loss: 0.2231312245130539
Epoch: 22 Loss: 0.21214650571346283
Epoch: 23 Loss: 0.20190170407295227
Epoch: 24 Loss: 0.19237388670444489
Epoch: 25 Loss: 0.18351155519485474
Epoch: 26 Loss: 0.17528857290744781
Epoch: 27 Loss: 0.16763775050640106
Epoch: 28 Loss: 0

In [74]:
#Evalution
from sklearn.metrics import accuracy_score


with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred_labels = torch.round(y_pred)
    acc = accuracy_score(y_test_tensor, y_pred_labels)
    print(f'Accuracy: {acc}')


Accuracy: 0.9473684210526315


In [76]:
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       93
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 97
Trainable params: 97
Non-trainable params: 0

<generator object Module.parameters at 0x7ea5de8dbae0>