In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name()}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.8701, 0.6155, 0.3346],
        [0.5171, 0.3294, 0.9689]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.5706, 0.4694, 0.8217],
        [0.8621, 0.6241, 0.8329]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:

torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[          356255743, 4605269115022606336, 4601207137891254272],
        [4606294443975245824, 4607154373200445440, 4604989296829530112]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

## Tensor Data Types

In [24]:
# find data type
x.dtype

torch.int64

In [25]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [38]:
x = torch.rand(2,2)
x

tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

In [59]:
# addition
x + 5
# substraction
x - 5
# multiplication
x * 10
# division
x*100/ 5
# int division
x*100 // 5
# mod
x*100/5 % 5  #priority using BODMAS rule


tensor([[4.0707, 4.1281],
        [3.2576, 2.8040]])

### 2. Element wise operation

In [60]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [62]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0250, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [68]:
c = torch.tensor([1, -2, 3, -4])

In [79]:
# abs
print(c.dtype)
torch.abs(c)

torch.int64


tensor([1, 2, 3, 4])

In [80]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [81]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [82]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [85]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [86]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [87]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [132]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e[0][0] = 15
e[1][0] = 0

In [133]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18.,  9.])

In [134]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.5000, 4.0000, 2.0000])

In [135]:
# median
torch.median(e)

tensor(2.)

In [136]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [137]:
# product
torch.prod(e)

tensor(0.)

In [138]:
# standard deviation
torch.std(e)

tensor(5.6833)

In [139]:
# variance
torch.var(e)

tensor(32.3000)

In [140]:
# argmax
print(e.flatten().shape)
print(torch.argmax(e.flatten()[1:]))
torch.argmax(e)


torch.Size([6])
tensor(3)


tensor(0)

In [142]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [148]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,5), low=0, high=10)

print(f)
print(g)

tensor([[3, 6, 7],
        [8, 1, 2]])
tensor([[3, 2, 7, 9, 3],
        [9, 7, 7, 5, 9],
        [2, 2, 4, 8, 9]])


In [149]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 77,  62,  91, 113, 126],
        [ 37,  27,  71,  93,  51]])

In [151]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [157]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 8],
        [6, 1],
        [7, 2]])

In [153]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 4.],
        [5., 6., 0.],
        [4., 5., 8.]])

In [154]:
# determinant
torch.det(h)

tensor(252.)

In [158]:
# inverse
torch.inverse(h)

tensor([[ 0.1905,  0.0476, -0.0952],
        [-0.1587,  0.1270,  0.0794],
        [ 0.0040, -0.1032,  0.1230]])

### 5. Comparison operations

In [159]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 9],
        [6, 1, 9]])
tensor([[6, 8, 1],
        [7, 5, 6]])


In [160]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True, False,  True],
        [ True,  True,  True]])

### 6. Special functions

In [161]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 8., 2.],
        [8., 8., 0.]])

In [163]:
# log
torch.log(k)

tensor([[2.1972, 2.0794, 0.6931],
        [2.0794, 2.0794,   -inf]])

In [164]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 2.9810e+03, 7.3891e+00],
        [2.9810e+03, 2.9810e+03, 1.0000e+00]])

In [165]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 2.8284, 1.4142],
        [2.8284, 2.8284, 0.0000]])

In [166]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9997, 0.8808],
        [0.9997, 0.9997, 0.5000]])

In [169]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.5000, 0.8808],
        [0.2689, 0.5000, 0.1192]])

In [171]:

# relu
torch.relu(k)

tensor([[9., 8., 2.],
        [8., 8., 0.]])

## Inplace Operations

In [172]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1041, 0.9193, 0.6201],
        [0.3658, 0.0623, 0.5967]])
tensor([[0.0829, 0.8185, 0.4964],
        [0.0589, 0.9840, 0.5836]])


In [173]:
m.add_(n)

tensor([[0.1870, 1.7378, 1.1165],
        [0.4247, 1.0463, 1.1803]])

In [174]:
m

tensor([[0.1870, 1.7378, 1.1165],
        [0.4247, 1.0463, 1.1803]])

In [175]:
n

tensor([[0.0829, 0.8185, 0.4964],
        [0.0589, 0.9840, 0.5836]])

In [176]:
torch.relu(m)

tensor([[0.1870, 1.7378, 1.1165],
        [0.4247, 1.0463, 1.1803]])

In [177]:
m.relu_()

tensor([[0.1870, 1.7378, 1.1165],
        [0.4247, 1.0463, 1.1803]])

In [178]:
m

tensor([[0.1870, 1.7378, 1.1165],
        [0.4247, 1.0463, 1.1803]])

## Copying a Tensor

In [179]:
a = torch.rand(2,3)
a

tensor([[0.6737, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [180]:
b = a

In [181]:
b

tensor([[0.6737, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [182]:
a[0][0] = 0

In [183]:
a

tensor([[0.0000, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [184]:
b

tensor([[0.0000, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [185]:
id(a)

134692138734160

In [186]:
id(b)

134692138734160

In [187]:
b = a.clone()

In [188]:
a

tensor([[0.0000, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [189]:
b

tensor([[0.0000, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [190]:
a[0][0] = 10

In [191]:
a

tensor([[10.0000,  0.4738,  0.9336],
        [ 0.2557,  0.1506,  0.7856]])

In [192]:
b

tensor([[0.0000, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [193]:
id(a)

134692138734160

In [194]:
id(b)

134692138734736